# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FacebookLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FacebookLogin

  pod 'FBSDKLoginKit'

  target 'FacebookLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FacebookLoginUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
